# 指定 Actions 的名稱，會顯示在 Actions 頁面上
name: deploy actions

# 指定觸發的事件(trigger event)，這裡是 push 到 main 分支時觸發
on:
  pull_request:
    types:
      - closed
    branches: main

# 指定工作流程(jobs)
# 每個 actions 至少要有一個 job
jobs:
  deploy-web:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Port number is ${{ secrets.EC2_PORT }}"
      - name: deploy to ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/cicd-pipeline-workshop
            git pull
            pm2 restart src/server.js
          # remove <none> TAG images
          #docker rmi $(docker images --filter "dang
